stages:
  - build

variables:
  KNT_ORIGINAL_PROJECT_PATH: "konnect/sequelize"
  KNT_BUILDER_TOOLS : "@konnect/builder-tools@^2000"
  KNT_PATH_BUILDER_TOOLS: "./.dglobal/lib/node_modules/@konnect/builder-tools"

build_branch:
  stage: build
  script: 
  # On récupère les scripts de build
  - npm install --prefix $CI_PROJECT_DIR/.dglobal/ $KNT_BUILDER_TOOLS -g
  # Mise en place des versions dans le package.json
  - (node $KNT_PATH_BUILDER_TOOLS/tasks/common/prepare-build-client.js) || exit 1;
  # Récupération du nom du projet
  - export KNT_PACKAGE_NAME=$(node $KNT_PATH_BUILDER_TOOLS/tasks/common/get-project-name)
  # Push to NPM sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/push-to-gogit.sh no_git $CI_COMMIT_REF_NAME $KNT_ORIGINAL_PROJECT_PATH $KNT_PACKAGE_NAME
  # Push to NPM @konnect/sequelize
  - node $KNT_PATH_BUILDER_TOOLS/tasks/common/set-project-name --name @konnect/sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/push-to-gogit.sh no_git $CI_COMMIT_REF_NAME $KNT_ORIGINAL_PROJECT_PATH @konnect/sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/clean-tmp.sh
  only:
  - master
  - develop
  
build_tag:
  stage: build
  script:
  # On récupère les scripts de build
  - npm install --prefix $CI_PROJECT_DIR/.dglobal/ $KNT_BUILDER_TOOLS -g
  # Mise en place des versions dans le package.json
  - (node $KNT_PATH_BUILDER_TOOLS/tasks/common/prepare-build-client.js) || exit 1;
  # Récupération du nom du projet
  - export KNT_PACKAGE_NAME=$(node $KNT_PATH_BUILDER_TOOLS/tasks/common/get-project-name)
  # Push to NPM sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/push-to-gogit.sh no_git tag $KNT_ORIGINAL_PROJECT_PATH $KNT_PACKAGE_NAME
  # Push to NPM @konnect/sequelize
  - node $KNT_PATH_BUILDER_TOOLS/tasks/common/set-project-name --name @konnect/sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/push-to-gogit.sh no_git tag $KNT_ORIGINAL_PROJECT_PATH @konnect/sequelize
  - $KNT_PATH_BUILDER_TOOLS/tasks/linux/common/clean-tmp.sh
  only:
  - tags

